"""Initial database schema

Revision ID: a7b77c5e63e9
Revises: 
Create Date: 2026-03-24 05:34:32.307516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b77c5e63e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_expense_shares_expense_id'), table_name='expense_shares')
    op.drop_index(op.f('idx_expense_shares_user_id'), table_name='expense_shares')
    op.drop_index(op.f('idx_expenses_group_id'), table_name='expenses')
    op.drop_index(op.f('idx_group_members_group_id'), table_name='group_members')
    op.drop_index(op.f('idx_group_members_user_id'), table_name='group_members')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('idx_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('idx_expenses_group_id'), 'expenses', ['group_id'], unique=False)
    op.create_index(op.f('idx_expense_shares_user_id'), 'expense_shares', ['user_id'], unique=False)
    op.create_index(op.f('idx_expense_shares_expense_id'), 'expense_shares', ['expense_id'], unique=False)
    # ### end Alembic commands ###
